// <auto-generated />
using System;
using Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Migrations
{
    [DbContext(typeof(WalkDbContext))]
    partial class WalkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1958455-e9c3-4735-877e-5c027507566a"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("77e275f6-3971-4df7-baa9-b671db84cfb0"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("b87727ba-4bf4-4f02-ae97-3ef980ad83c7"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Domain.Ragion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region_UmageUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ragions");
                });

            modelBuilder.Entity("Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("char(36)");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double");

                    b.Property<Guid>("RagionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Region_UmageUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RagionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Domain.Walk", b =>
                {
                    b.HasOne("Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Build_ASP.NET_Core_Web_API___Scratch_To_Finish.Domain.Ragion", "Ragion")
                        .WithMany()
                        .HasForeignKey("RagionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Ragion");
                });
#pragma warning restore 612, 618
        }
    }
}
